# Generated by Django 3.1.4 on 2022-02-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Date_Of_Joining',
            new_name='DateOfJoining',
        ),
    ]
